Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -52,11 +52,13 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
 
         # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
-        # Use || true to not fail the pipeline
+        # Use || true to not fail the pipeline 
+      - name: snyk auth
+        run: snyk auth 536d3fde-120a-4ef5-b434-1eedd9f5b4ef 
+        #--sarif > snyk-code.sarif # || true  
       - name: Snyk Code test
         run: snyk code test 
         #--sarif > snyk-code.sarif # || true
-
         # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
       - name: Snyk Open Source monitor
         run: snyk monitor --all-projects
